<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FB_Module" Id="{b6184298-8309-4406-9099-e98708c7ef5d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Module
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Module">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>